backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Publish Date', name: 'createdAt', widget: 'datetime' }
      - { label: 'Created By', name: 'createdBy', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }